[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.13",
    "nextcord>=2.6.0",
    "spotipy>=2.25.1",
    "wavelink>=3.4.1",
    "yt-dlp>=2025.2.19",
]
